# Generated by Django 5.0.2 on 2024-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_totalloan_totaltake'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mission_complete',
            field=models.BooleanField(default=False),
        ),
    ]
