# Generated by Django 4.2 on 2024-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customer_mission_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AddField(
            model_name='document',
            name='cus_nid',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='cus_photo',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='cus_stamp',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='jamin_nid',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='jamin_photo',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
        migrations.AddField(
            model_name='document',
            name='jamin_stamp',
            field=models.FileField(blank=True, null=True, upload_to='customer-documents'),
        ),
    ]
