# Generated by Django 5.0.2 on 2024-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_document_file_remove_document_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
