# Generated by Django 5.0.2 on 2024-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
