# Generated by Django 4.2 on 2024-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='member'),
        ),
    ]
